package app

import (
	"bufio"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

// Config stores pull sources, push targets, and local WordPress behavior.
type Config struct {
	Provider          string
	User              string
	Host              string
	Port              string
	RemotePath        string
	RemoteTmpDir      string
	PushUser          string
	PushHost          string
	PushPort          string
	PushRemotePath    string
	PushRemoteTmpDir  string
	PushURL           string
	LocalWPPath       string
	CloneImages       bool
	PluginRemoveFile  string
	LocalURL          string
	SkipSearchReplace bool
}

var (
	validSSHPart    = regexp.MustCompile(`^[A-Za-z0-9._-]+$`)
	validPluginPath = regexp.MustCompile(`^[A-Za-z0-9._/-]+$`)
)

// defaultConfig returns silent-mode defaults shared by pull and push commands.
func defaultConfig() Config {
	return Config{
		Provider:         defaultProviderName,
		RemoteTmpDir:     "/tmp",
		PushRemoteTmpDir: "/tmp",
	}
}

// loadConfig reads the config file for the selected runtime and applies environment overrides.
func loadConfig(projectRoot string) (Config, error) {
	return loadConfigPath(projectConfigPath(projectRoot))
}

// loadStandaloneConfig reads the standalone config file and applies environment overrides.
func loadStandaloneConfig(root string) (Config, error) {
	return loadConfigPath(standaloneConfigPath(root))
}

func loadConfigPath(path string) (Config, error) {
	cfg := defaultConfig()
	if _, err := os.Stat(path); err == nil {
		loaded, err := readConfigFile(path)
		if err != nil {
			return cfg, err
		}
		cfg = mergeConfig(cfg, loaded)
	} else if !errors.Is(err, os.ErrNotExist) {
		return cfg, err
	}

	cfg.applyEnv(os.Environ())
	return cfg, nil
}

// readConfigFile parses the small YAML subset emitted by writeConfigFile.
func readConfigFile(path string) (Config, error) {
	cfg := Config{}
	file, err := os.Open(path)
	if err != nil {
		return cfg, err
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		key, raw, ok := strings.Cut(line, ":")
		if !ok {
			return cfg, fmt.Errorf("invalid config line in %s: %s", path, line)
		}

		key = strings.TrimSpace(key)
		value := strings.TrimSpace(raw)
		if strings.HasPrefix(value, "#") {
			value = ""
		}

		if unquoted, err := strconv.Unquote(value); err == nil {
			value = unquoted
		}

		switch key {
		case "provider":
			cfg.Provider = value
		case "pull_user", "user":
			cfg.User = value
		case "pull_host", "host":
			cfg.Host = value
		case "pull_port", "port":
			cfg.Port = value
		case "pull_remote_path", "remote_path":
			cfg.RemotePath = value
		case "pull_remote_tmp_dir", "remote_tmp_dir":
			cfg.RemoteTmpDir = value
		case "push_user":
			cfg.PushUser = value
		case "push_host":
			cfg.PushHost = value
		case "push_port":
			cfg.PushPort = value
		case "push_remote_path":
			cfg.PushRemotePath = value
		case "push_remote_tmp_dir":
			cfg.PushRemoteTmpDir = value
		case "push_url":
			cfg.PushURL = value
		case "local_wp_path":
			cfg.LocalWPPath = value
		case "clone_images":
			cfg.CloneImages = parseBool(value)
		case "plugin_remove_file":
			cfg.PluginRemoveFile = value
		case "local_url":
			cfg.LocalURL = value
		case "skip_search_replace":
			cfg.SkipSearchReplace = parseBool(value)
		default:
			return cfg, fmt.Errorf("unknown config key %q in %s", key, path)
		}
	}

	if err := scanner.Err(); err != nil {
		return cfg, err
	}

	return cfg, nil
}

// writeConfigFile persists the CLI-owned YAML without touching DDEV config files.
func writeConfigFile(path string, cfg Config) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}

	body := strings.Builder{}
	body.WriteString("# ddev-wp-ssh project config. Generated by `ddev-wp-ssh init`.\n")
	body.WriteString(fmt.Sprintf("provider: %s\n", quoteYAML(cfg.Provider)))
	body.WriteString(fmt.Sprintf("pull_user: %s\n", quoteYAML(cfg.User)))
	body.WriteString(fmt.Sprintf("pull_host: %s\n", quoteYAML(cfg.Host)))
	body.WriteString(fmt.Sprintf("pull_port: %s\n", quoteYAML(cfg.Port)))
	body.WriteString(fmt.Sprintf("pull_remote_path: %s\n", quoteYAML(cfg.RemotePath)))
	body.WriteString(fmt.Sprintf("pull_remote_tmp_dir: %s\n", quoteYAML(defaultString(cfg.RemoteTmpDir, "/tmp"))))
	body.WriteString(fmt.Sprintf("push_user: %s\n", quoteYAML(cfg.PushUser)))
	body.WriteString(fmt.Sprintf("push_host: %s\n", quoteYAML(cfg.PushHost)))
	body.WriteString(fmt.Sprintf("push_port: %s\n", quoteYAML(cfg.PushPort)))
	body.WriteString(fmt.Sprintf("push_remote_path: %s\n", quoteYAML(cfg.PushRemotePath)))
	body.WriteString(fmt.Sprintf("push_remote_tmp_dir: %s\n", quoteYAML(defaultString(cfg.PushRemoteTmpDir, "/tmp"))))
	body.WriteString(fmt.Sprintf("push_url: %s\n", quoteYAML(cfg.PushURL)))
	body.WriteString(fmt.Sprintf("local_wp_path: %s\n", quoteYAML(cfg.LocalWPPath)))
	body.WriteString(fmt.Sprintf("clone_images: %t\n", cfg.CloneImages))
	body.WriteString(fmt.Sprintf("plugin_remove_file: %s\n", quoteYAML(cfg.PluginRemoveFile)))
	body.WriteString(fmt.Sprintf("local_url: %s\n", quoteYAML(cfg.LocalURL)))
	body.WriteString(fmt.Sprintf("skip_search_replace: %t\n", cfg.SkipSearchReplace))

	return os.WriteFile(path, []byte(body.String()), 0o644)
}

// applyEnv overlays WP_SSH_* variables for provider compatibility.
func (cfg *Config) applyEnv(env []string) {
	values := envMap(env)
	cfg.User = firstNonEmpty(values["WP_SSH_PULL_USER"], cfg.User)
	cfg.Host = firstNonEmpty(values["WP_SSH_PULL_HOST"], cfg.Host)
	cfg.Port = firstNonEmpty(values["WP_SSH_PULL_PORT"], cfg.Port)
	cfg.RemotePath = firstNonEmpty(values["WP_SSH_PULL_REMOTE_PATH"], cfg.RemotePath)
	cfg.RemoteTmpDir = firstNonEmpty(values["WP_SSH_PULL_REMOTE_TMP_DIR"], cfg.RemoteTmpDir)
	cfg.PushUser = firstNonEmpty(values["WP_SSH_PUSH_USER"], cfg.PushUser)
	cfg.PushHost = firstNonEmpty(values["WP_SSH_PUSH_HOST"], cfg.PushHost)
	cfg.PushPort = firstNonEmpty(values["WP_SSH_PUSH_PORT"], cfg.PushPort)
	cfg.PushRemotePath = firstNonEmpty(values["WP_SSH_PUSH_REMOTE_PATH"], cfg.PushRemotePath)
	cfg.PushRemoteTmpDir = firstNonEmpty(values["WP_SSH_PUSH_REMOTE_TMP_DIR"], cfg.PushRemoteTmpDir)
	cfg.PushURL = firstNonEmpty(values["WP_SSH_PUSH_URL"], cfg.PushURL)
	cfg.LocalWPPath = firstNonEmpty(values["WP_SSH_LOCAL_WP_PATH"], values["WP_SSH_PULL_LOCAL_WP_PATH"], cfg.LocalWPPath)
	cfg.PluginRemoveFile = firstNonEmpty(values["WP_SSH_PULL_PLUGIN_REMOVE_FILE"], cfg.PluginRemoveFile)
	cfg.LocalURL = firstNonEmpty(values["WP_SSH_PULL_LOCAL_URL"], cfg.LocalURL)
	cfg.Provider = firstNonEmpty(values["WP_SSH_PROVIDER"], cfg.Provider)

	if value, ok := values["WP_SSH_PULL_CLONE_IMAGES"]; ok {
		cfg.CloneImages = parseBool(value)
	}
	if value, ok := values["WP_SSH_PULL_SKIP_SEARCH_REPLACE"]; ok {
		cfg.SkipSearchReplace = parseBool(value)
	}
	if value, ok := values["WP_SSH_PUSH_SKIP_SEARCH_REPLACE"]; ok {
		cfg.SkipSearchReplace = parseBool(value)
	}
}

// RemoteTarget stores the SSH and WordPress root fields for one operation.
type RemoteTarget struct {
	User         string
	Host         string
	Port         string
	RemotePath   string
	RemoteTmpDir string
}

// pullTarget returns the configured upstream source.
func (cfg Config) pullTarget() RemoteTarget {
	return RemoteTarget{
		User:         cfg.User,
		Host:         cfg.Host,
		Port:         cfg.Port,
		RemotePath:   cfg.RemotePath,
		RemoteTmpDir: defaultString(cfg.RemoteTmpDir, "/tmp"),
	}
}

// pushTarget returns the configured upstream deployment target.
func (cfg Config) pushTarget() RemoteTarget {
	return RemoteTarget{
		User:         cfg.PushUser,
		Host:         cfg.PushHost,
		Port:         cfg.PushPort,
		RemotePath:   cfg.PushRemotePath,
		RemoteTmpDir: defaultString(cfg.PushRemoteTmpDir, "/tmp"),
	}
}

// validatePullRequired ensures source commands cannot be built from unsafe values.
func (cfg Config) validatePullRequired() error {
	return cfg.pullTarget().validate("pull source", "configure pull_user, pull_host, and pull_remote_path in wp-ssh.yaml, set WP_SSH_PULL_* env vars, or pass --user, --host, and --remote-path")
}

// validatePushRequired ensures push commands cannot be built from unsafe values.
func (cfg Config) validatePushRequired() error {
	return cfg.pushTarget().validate("push target", "set push_* config or pass --push-user, --push-host, and --push-remote-path")
}

// validateConfiguredPush validates a push target only when one was configured.
func (cfg Config) validateConfiguredPush() error {
	if !cfg.pushTarget().configured() {
		return nil
	}
	return cfg.validatePushRequired()
}

// validateInitValues permits partial setup while rejecting unsafe provided values.
func (cfg Config) validateInitValues() error {
	if err := cfg.pullTarget().validateValues("pull source"); err != nil {
		return err
	}
	return cfg.pushTarget().validateValues("push target")
}

// validate checks that SSH and remote path values are safe for command construction.
func (target RemoteTarget) validate(label string, help string) error {
	if target.User == "" {
		return fmt.Errorf("missing SSH user for %s; %s", label, help)
	}
	if target.Host == "" {
		return fmt.Errorf("missing SSH host for %s; %s", label, help)
	}
	if target.RemotePath == "" {
		return fmt.Errorf("missing remote WordPress path for %s; %s", label, help)
	}
	return target.validateValues(label)
}

// validateValues checks provided target values without requiring a complete target.
func (target RemoteTarget) validateValues(label string) error {
	if target.User != "" && !validSSHPart.MatchString(target.User) {
		return fmt.Errorf("user for %s must contain only letters, numbers, dots, underscores, or hyphens", label)
	}
	if target.Host != "" && !validSSHPart.MatchString(target.Host) {
		return fmt.Errorf("host for %s must contain only letters, numbers, dots, underscores, or hyphens", label)
	}
	if target.Port != "" {
		if _, err := strconv.Atoi(target.Port); err != nil {
			return fmt.Errorf("port for %s must be numeric", label)
		}
	}
	if strings.ContainsAny(target.RemotePath, "\r\n") {
		return fmt.Errorf("remote path for %s must not contain newlines", label)
	}
	if strings.ContainsAny(defaultString(target.RemoteTmpDir, "/tmp"), "\r\n") {
		return fmt.Errorf("remote tmp dir for %s must not contain newlines", label)
	}
	return nil
}

// configured reports whether any field for the target has been provided.
func (target RemoteTarget) configured() bool {
	return target.User != "" || target.Host != "" || target.Port != "" || target.RemotePath != ""
}

// envArgs converts configuration into DDEV's legacy --environment payload.
func (cfg Config) envArgs() string {
	pairs := []string{}
	add := func(key, value string) {
		if value != "" {
			pairs = append(pairs, key+"="+value)
		}
	}

	add("WP_SSH_PULL_USER", cfg.User)
	add("WP_SSH_PULL_HOST", cfg.Host)
	add("WP_SSH_PULL_PORT", cfg.Port)
	add("WP_SSH_PULL_REMOTE_PATH", cfg.RemotePath)
	add("WP_SSH_PULL_REMOTE_TMP_DIR", cfg.RemoteTmpDir)
	add("WP_SSH_PUSH_USER", cfg.PushUser)
	add("WP_SSH_PUSH_HOST", cfg.PushHost)
	add("WP_SSH_PUSH_PORT", cfg.PushPort)
	add("WP_SSH_PUSH_REMOTE_PATH", cfg.PushRemotePath)
	add("WP_SSH_PUSH_REMOTE_TMP_DIR", cfg.PushRemoteTmpDir)
	add("WP_SSH_PUSH_URL", cfg.PushURL)
	add("WP_SSH_LOCAL_WP_PATH", cfg.LocalWPPath)
	add("WP_SSH_PULL_LOCAL_WP_PATH", cfg.LocalWPPath)
	add("WP_SSH_PULL_PLUGIN_REMOVE_FILE", cfg.PluginRemoveFile)
	add("WP_SSH_PULL_LOCAL_URL", cfg.LocalURL)
	add("WP_SSH_PROVIDER", cfg.Provider)
	pairs = append(pairs, fmt.Sprintf("WP_SSH_PULL_CLONE_IMAGES=%t", cfg.CloneImages))
	pairs = append(pairs, fmt.Sprintf("WP_SSH_PULL_SKIP_SEARCH_REPLACE=%t", cfg.SkipSearchReplace))
	pairs = append(pairs, fmt.Sprintf("WP_SSH_PUSH_SKIP_SEARCH_REPLACE=%t", cfg.SkipSearchReplace))

	return strings.Join(pairs, ",")
}

// mergeConfig overlays non-zero values while preserving explicit false booleans from the base.
func mergeConfig(base Config, overlay Config) Config {
	if overlay.Provider != "" {
		base.Provider = overlay.Provider
	}
	if overlay.User != "" {
		base.User = overlay.User
	}
	if overlay.Host != "" {
		base.Host = overlay.Host
	}
	if overlay.Port != "" {
		base.Port = overlay.Port
	}
	if overlay.RemotePath != "" {
		base.RemotePath = overlay.RemotePath
	}
	if overlay.RemoteTmpDir != "" {
		base.RemoteTmpDir = overlay.RemoteTmpDir
	}
	if overlay.PushUser != "" {
		base.PushUser = overlay.PushUser
	}
	if overlay.PushHost != "" {
		base.PushHost = overlay.PushHost
	}
	if overlay.PushPort != "" {
		base.PushPort = overlay.PushPort
	}
	if overlay.PushRemotePath != "" {
		base.PushRemotePath = overlay.PushRemotePath
	}
	if overlay.PushRemoteTmpDir != "" {
		base.PushRemoteTmpDir = overlay.PushRemoteTmpDir
	}
	if overlay.PushURL != "" {
		base.PushURL = overlay.PushURL
	}
	if overlay.LocalWPPath != "" {
		base.LocalWPPath = overlay.LocalWPPath
	}
	if overlay.PluginRemoveFile != "" {
		base.PluginRemoveFile = overlay.PluginRemoveFile
	}
	if overlay.LocalURL != "" {
		base.LocalURL = overlay.LocalURL
	}
	base.CloneImages = overlay.CloneImages || base.CloneImages
	base.SkipSearchReplace = overlay.SkipSearchReplace || base.SkipSearchReplace
	return base
}

// projectConfigPath returns the CLI-owned project config location.
func projectConfigPath(projectRoot string) string {
	return filepath.Join(projectRoot, ".ddev", configFileName)
}

// standaloneConfigPath returns the config path used outside DDEV projects.
func standaloneConfigPath(root string) string {
	return filepath.Join(root, ".wp-ssh.yaml")
}

// pluginListPath returns the editable plugin block list path.
func pluginListPath(projectRoot string, cfg Config) string {
	if cfg.PluginRemoveFile != "" {
		if filepath.IsAbs(cfg.PluginRemoveFile) {
			return cfg.PluginRemoveFile
		}
		return filepath.Join(projectRoot, cfg.PluginRemoveFile)
	}
	if hasDDEVConfig(projectRoot) {
		return filepath.Join(projectRoot, ".ddev", "wp-ssh-plugins.txt")
	}
	return filepath.Join(projectRoot, ".wp-ssh-plugins.txt")
}

// quoteYAML writes a conservative scalar compatible with YAML parsers.
func quoteYAML(value string) string {
	return strconv.Quote(value)
}

// parseBool accepts the truthy values supported by the old shell provider.
func parseBool(value string) bool {
	switch strings.ToLower(strings.TrimSpace(value)) {
	case "1", "true", "yes", "on":
		return true
	default:
		return false
	}
}

// envMap converts os.Environ-style values into a lookup map.
func envMap(env []string) map[string]string {
	values := make(map[string]string, len(env))
	for _, item := range env {
		key, value, ok := strings.Cut(item, "=")
		if ok {
			values[key] = value
		}
	}
	return values
}

func firstNonEmpty(values ...string) string {
	for _, value := range values {
		if value != "" {
			return value
		}
	}
	return ""
}

func defaultString(value string, fallback string) string {
	if value == "" {
		return fallback
	}
	return value
}
