package app

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const defaultPluginList = `# One plugin slug or plugin basename per line.
# Listed plugins are excluded from upstream pulls and deactivated locally.
# Mounted or symlinked package directories are never deleted.

# Backup, migration, and restore plugins.
wpvivid-backuprestore
updraftplus
updraftplus-premium
duplicator
duplicator-pro
all-in-one-wp-migration
all-in-one-wp-migration-unlimited-extension
backwpup
backupwordpress
backup-backup
blogvault-real-time-backup
boldgrid-backup
migrate-guru
wp-db-backup
wp-migrate-db
wp-staging
xcloner-backup-and-restore

# SMTP and mail delivery plugins.
wp-mail-smtp
post-smtp
easy-wp-smtp
fluent-smtp
smtp-mailer
wp-smtp
gmail-smtp
mailgun
mailjet-for-wordpress
postmark-approved-wordpress-plugin
sendinblue
sendgrid-email-delivery-simplified
mailersend-official-smtp-integration
smtp2go
wp-offload-ses-lite
`

// providerYAML renders the DDEV provider that delegates to this host CLI.
func providerYAML(providerName string, binary string) string {
	installCommand := shellCommand(binary, "provider", "install", "--provider", providerName)
	return fmt.Sprintf(`# Generated by wp-ssh-bridge. Re-run %s after CLI updates.
# Pull and push provider for SSH-only WordPress upstreams.

info_command:
  service: host
  command: %s

auth_command:
  service: host
  command: %s

db_pull_command:
  service: host
  command: %s

files_pull_command:
  service: host
  command: %s

files_import_command:
  service: host
  command: %s

db_push_command:
  service: host
  command: %s

files_push_command:
  service: host
  command: %s
`, installCommand,
		quoteYAML(shellCommand(binary, "provider", "info")),
		quoteYAML(shellCommand(binary, "provider", "auth")),
		quoteYAML(shellCommand(binary, "provider", "db-pull")),
		quoteYAML(shellCommand(binary, "provider", "files-pull")),
		quoteYAML(shellCommand(binary, "provider", "files-import")),
		quoteYAML(shellCommand(binary, "provider", "db-push")),
		quoteYAML(shellCommand(binary, "provider", "files-push")),
	)
}

// hookYAML renders post-operation hooks that keep cleanup in Go.
func hookYAML(binary string) string {
	installCommand := shellCommand(binary, "provider", "install")
	return fmt.Sprintf(`# Generated by wp-ssh-bridge. Re-run %s after CLI updates.
hooks:
  post-pull:
    - exec-host: %s
  post-push:
    - exec-host: %s
`, installCommand,
		quoteYAML(shellCommand(binary, "provider", "post-pull")),
		quoteYAML(shellCommand(binary, "provider", "post-push")),
	)
}

// shellCommand renders a command string for DDEV YAML without over-quoting safe words.
func shellCommand(args ...string) string {
	words := make([]string, 0, len(args))
	for _, arg := range args {
		if isSafeShellWord(arg) {
			words = append(words, arg)
			continue
		}
		words = append(words, shellQuote(arg))
	}
	return strings.Join(words, " ")
}

// isSafeShellWord permits the characters commonly used in executable paths and flags.
func isSafeShellWord(value string) bool {
	if value == "" {
		return false
	}
	for _, char := range value {
		if char >= 'A' && char <= 'Z' || char >= 'a' && char <= 'z' || char >= '0' && char <= '9' {
			continue
		}
		switch char {
		case '_', '-', '.', '/', ':', '@', '%', '+', '=', ',':
			continue
		default:
			return false
		}
	}
	return true
}

// installProviderFiles writes provider and hook files without installing a DDEV add-on.
func installProviderFiles(projectRoot string, cfg Config, binary string) error {
	providerName := defaultString(cfg.Provider, defaultProviderName)
	if err := validateProviderName(providerName); err != nil {
		return err
	}
	binary = portableProviderBinary(projectRoot, binary)
	if err := os.MkdirAll(filepath.Join(projectRoot, ".ddev", "providers"), 0o755); err != nil {
		return err
	}

	providerPath := filepath.Join(projectRoot, ".ddev", "providers", providerName+".yaml")
	if err := os.WriteFile(providerPath, []byte(providerYAML(providerName, binary)), 0o644); err != nil {
		return err
	}

	hookPath := filepath.Join(projectRoot, ".ddev", hookConfigName)
	if err := os.WriteFile(hookPath, []byte(hookYAML(binary)), 0o644); err != nil {
		return err
	}

	return ensureCustomPluginList(projectRoot, cfg)
}

// portableProviderBinary keeps generated DDEV YAML free of project-local absolute paths.
func portableProviderBinary(projectRoot string, binary string) string {
	if binary == "" {
		return binaryName
	}
	if !filepath.IsAbs(binary) {
		return filepath.ToSlash(binary)
	}
	if rel, ok := projectRelativePath(projectRoot, binary); ok {
		return "./" + rel
	}
	if filepath.Base(binary) == binaryName {
		return binaryName
	}
	return binary
}

// installStandaloneFiles writes standalone support files without DDEV provider YAML.
func installStandaloneFiles(root string, cfg Config) error {
	return ensureCustomPluginList(root, cfg)
}

func ensureCustomPluginList(root string, cfg Config) error {
	if cfg.PluginRemoveFile == "" {
		return nil
	}

	listPath := pluginListPath(root, cfg)
	if _, err := os.Stat(listPath); err == nil {
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(listPath), 0o755); err != nil {
		return err
	}
	return os.WriteFile(listPath, []byte(defaultPluginList), 0o644)
}

// generatedFilesReport describes files managed by provider install.
func generatedFilesReport(projectRoot string, cfg Config) string {
	providerName := defaultString(cfg.Provider, defaultProviderName)
	paths := []string{
		filepath.Join(projectRoot, ".ddev", "providers", providerName+".yaml"),
		filepath.Join(projectRoot, ".ddev", hookConfigName),
		projectConfigPath(projectRoot),
	}
	if cfg.PluginRemoveFile != "" {
		paths = append(paths, pluginListPath(projectRoot, cfg))
	}
	return strings.Join(paths, "\n")
}
