package app

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const defaultPluginList = `# One plugin slug or plugin basename per line.
# Listed plugins are excluded from upstream pulls and deactivated locally.
# Mounted or symlinked package directories are never deleted.

# Backup, migration, and restore plugins.
wpvivid-backuprestore
updraftplus
updraftplus-premium
duplicator
duplicator-pro
all-in-one-wp-migration
all-in-one-wp-migration-unlimited-extension
backwpup
backupwordpress
backup-backup
blogvault-real-time-backup
boldgrid-backup
migrate-guru
wp-db-backup
wp-migrate-db
wp-staging
xcloner-backup-and-restore

# SMTP and mail delivery plugins.
wp-mail-smtp
post-smtp
easy-wp-smtp
fluent-smtp
smtp-mailer
wp-smtp
gmail-smtp
mailgun
mailjet-for-wordpress
postmark-approved-wordpress-plugin
sendinblue
sendgrid-email-delivery-simplified
mailersend-official-smtp-integration
smtp2go
wp-offload-ses-lite
`

// providerYAML renders the DDEV provider that delegates to this CLI inside DDEV.
func providerYAML(providerName string, binary string) string {
	return fmt.Sprintf(`# Generated by ddev-wp-ssh. Re-run %q after CLI updates.
# Pull and push provider for SSH-only WordPress upstreams.

info_command:
  service: web
  command: %s provider info

auth_command:
  service: web
  command: %s provider auth

db_pull_command:
  service: web
  command: %s provider db-pull

files_pull_command:
  service: web
  command: %s provider files-pull

files_import_command:
  service: web
  command: %s provider files-import

db_push_command:
  service: web
  command: %s provider db-push

files_push_command:
  service: web
  command: %s provider files-push
`, binary+" provider install --provider "+providerName, binary, binary, binary, binary, binary, binary, binary)
}

// hookYAML renders post-operation hooks that keep cleanup inside DDEV.
func hookYAML(binary string) string {
	return fmt.Sprintf(`# Generated by ddev-wp-ssh. Re-run %q after CLI updates.
hooks:
  post-pull:
    - exec: %s provider post-pull
  post-push:
    - exec: %s provider post-push
`, binary+" provider install", binary, binary)
}

// installProviderFiles writes provider and hook files without installing a DDEV add-on.
func installProviderFiles(projectRoot string, cfg Config, binary string) error {
	providerName := defaultString(cfg.Provider, defaultProviderName)
	if err := os.MkdirAll(filepath.Join(projectRoot, ".ddev", "providers"), 0o755); err != nil {
		return err
	}

	containerBinary, err := ddevProviderBinaryPath(projectRoot, binary)
	if err != nil {
		return err
	}

	providerPath := filepath.Join(projectRoot, ".ddev", "providers", providerName+".yaml")
	if err := os.WriteFile(providerPath, []byte(providerYAML(providerName, containerBinary)), 0o644); err != nil {
		return err
	}

	hookPath := filepath.Join(projectRoot, ".ddev", hookConfigName)
	if err := os.WriteFile(hookPath, []byte(hookYAML(containerBinary)), 0o644); err != nil {
		return err
	}

	return ensureCustomPluginList(projectRoot, cfg)
}

// installStandaloneFiles writes standalone support files without DDEV provider YAML.
func installStandaloneFiles(root string, cfg Config) error {
	return ensureCustomPluginList(root, cfg)
}

func ensureCustomPluginList(root string, cfg Config) error {
	if cfg.PluginRemoveFile == "" {
		return nil
	}

	listPath := pluginListPath(root, cfg)
	if _, err := os.Stat(listPath); err == nil {
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(listPath), 0o755); err != nil {
		return err
	}
	return os.WriteFile(listPath, []byte(defaultPluginList), 0o644)
}

// generatedFilesReport describes files managed by provider install.
func generatedFilesReport(projectRoot string, cfg Config) string {
	providerName := defaultString(cfg.Provider, defaultProviderName)
	paths := []string{
		filepath.Join(projectRoot, ".ddev", "providers", providerName+".yaml"),
		filepath.Join(projectRoot, ".ddev", hookConfigName),
		projectConfigPath(projectRoot),
	}
	if cfg.PluginRemoveFile != "" {
		paths = append(paths, pluginListPath(projectRoot, cfg))
	}
	return strings.Join(paths, "\n")
}

func ddevProviderBinaryPath(projectRoot string, binary string) (string, error) {
	if binary == "" {
		return "", nil
	}
	if !filepath.IsAbs(binary) {
		return binary, nil
	}

	companion := filepath.Join(filepath.Dir(binary), binaryName+"-container")
	if _, err := os.Stat(companion); err == nil {
		return containerBinaryPath(projectRoot, companion)
	}
	if filepath.Base(binary) != binaryName+"-container" {
		return "", fmt.Errorf("DDEV provider execution requires %s next to %s; download a release archive that includes the container binary", companion, binary)
	}
	return containerBinaryPath(projectRoot, binary)
}

func containerBinaryPath(projectRoot string, binary string) (string, error) {
	if binary == "" {
		return "", nil
	}
	if !filepath.IsAbs(binary) {
		return binary, nil
	}
	rel, err := filepath.Rel(projectRoot, binary)
	if err != nil || strings.HasPrefix(rel, ".."+string(filepath.Separator)) || rel == ".." {
		return "", fmt.Errorf("DDEV provider binary %q must be inside the project so it is available in the web container", binary)
	}
	return "/var/www/html/" + filepath.ToSlash(rel), nil
}
